name: PR style and tests checker

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🔌
        uses: actions/checkout@v3
            
      - name: Npm install 🛒
        run: npm install --legacy-peer-deps
      
      - name: Lint 📝
        run: npm run lint
      
      - name: Test 📝
        run: npm run test

