name: Push master - Deploy to github pages.

on:
    push:
        branches:
            - master

jobs:
    build-and-deploy-to-gh:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout 🔌
              uses: actions/checkout@v3

            - name: Npm install 🛒
              run: npm install --legacy-peer-deps
      
            - name: Build 🔨
              run: npm run build
      
            - name: Deploy to GH 🚀
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                folder: build
                token: ${{ secrets.GITHUB_TOKEN }}
